package party.jml.partyboi.compos.admin

object SceneOrgUploadScripts {
    const val FTP_HOST = "ftp.scene.org"
    const val BASH_FILENAME = "upload.sh"
    const val BATCH_FILENAME = "upload.bat"

    fun bashScript(partyName: String, partyYear: Int): String = """
        #!/usr/bin/env bash
        # Uploads this directory to files.scene.org via anonymous FTP.
        # Run with:  bash upload.sh
        # Generated by Partyboi.

        set -euo pipefail

        PARTY_NAME="$partyName"
        PARTY_YEAR="$partyYear"
        FTP_HOST="$FTP_HOST"
        REMOTE_BASE="/incoming/parties/${'$'}{PARTY_YEAR}/${'$'}{PARTY_NAME}"

        cd "${'$'}(dirname "${'$'}{BASH_SOURCE[0]}")"
        ROOT="${'$'}(pwd)"

        echo "About to upload contents of ${'$'}{ROOT} to ftp://${'$'}{FTP_HOST}${'$'}{REMOTE_BASE}/"
        echo

        read -rp "Your email address (used as anonymous FTP password): " EMAIL
        if [ -z "${'$'}{EMAIL}" ]; then
            echo "Email is required."
            exit 1
        fi

        read -rp "Upload? [y/N] " CONFIRM
        case "${'$'}{CONFIRM}" in
            y|Y) ;;
            *) echo "Aborted."; exit 1 ;;
        esac

        if ! command -v curl >/dev/null 2>&1; then
            echo "Error: curl is required but not installed."
            exit 1
        fi

        count=0
        while IFS= read -r -d '' file; do
            rel="${'$'}{file#./}"
            case "${'$'}{rel}" in
                $BASH_FILENAME|$BATCH_FILENAME) continue ;;
            esac
            echo "  -> ${'$'}{rel}"
            curl --silent --show-error --fail --ftp-create-dirs \
                --user "anonymous:${'$'}{EMAIL}" \
                -T "${'$'}{file}" \
                "ftp://${'$'}{FTP_HOST}${'$'}{REMOTE_BASE}/${'$'}{rel}"
            count=${'$'}((count + 1))
        done < <(find . -type f -print0)

        echo
        echo "Uploaded ${'$'}{count} file(s). scene.org staff will move them out of /incoming/ within a day or two."
    """.trimIndent() + "\n"

    fun batchScript(partyName: String, partyYear: Int): String = """
        @echo off
        REM Uploads this directory to files.scene.org via anonymous FTP.
        REM Double-click this file, or run from a Command Prompt.
        REM Generated by Partyboi.

        setlocal EnableExtensions EnableDelayedExpansion
        cd /d "%~dp0"
        set "ROOT=%CD%"

        set "PARTY_NAME=$partyName"
        set "PARTY_YEAR=$partyYear"
        set "FTP_HOST=$FTP_HOST"
        set "REMOTE_BASE=/incoming/parties/%PARTY_YEAR%/%PARTY_NAME%"

        echo About to upload contents of %ROOT% to ftp://%FTP_HOST%%REMOTE_BASE%/
        echo.

        set /p "EMAIL=Your email address (used as anonymous FTP password): "
        if "!EMAIL!"=="" (
            echo Email is required.
            pause
            exit /b 1
        )

        set /p "CONFIRM=Upload? [y/N] "
        if /i not "!CONFIRM!"=="y" (
            echo Aborted.
            pause
            exit /b 1
        )

        where curl >nul 2>&1
        if errorlevel 1 (
            echo Error: curl is required. curl ships with Windows 10 version 1803 or later.
            pause
            exit /b 1
        )

        set /a COUNT=0
        for /r %%f in (*) do (
            set "FULL=%%f"
            set "REL=!FULL:%ROOT%\=!"
            set "REL=!REL:\=/!"
            if /i not "!REL!"=="$BASH_FILENAME" if /i not "!REL!"=="$BATCH_FILENAME" (
                echo   ^> !REL!
                curl --silent --show-error --fail --ftp-create-dirs --user "anonymous:!EMAIL!" -T "!FULL!" "ftp://%FTP_HOST%%REMOTE_BASE%/!REL!"
                if errorlevel 1 (
                    echo Upload failed for !REL!
                    pause
                    exit /b 1
                )
                set /a COUNT+=1
            )
        )

        echo.
        echo Uploaded !COUNT! file^(s^). scene.org staff will move them out of /incoming/ within a day or two.
        pause
    """.trimIndent().replace("\n", "\r\n") + "\r\n"
}
